### ISSUE TITLE
Ability to push to remote?

### ISSUE THREAD

**Issue by rpd10** [Axosoft/nodegit-flow#18]
I'm interested in using this in a CI setup, where after starting a release the CI server should push the new remote branch up to the remote.  Is this possible in the current version?

**Comment by jdgarcia** [comment]
When you do `var nodegit = require('nodegit-flow');`, you get a version of the [nodegit package](https://github.com/nodegit/nodegit/) that has extra gitflow functionality. All the base nodegit functionality (like pushing to a remote) is still available.

A push example can be found here: https://github.com/nodegit/nodegit/blob/master/examples/push.js
